# What is PyTorch

In [8]:
import torch

## Tensors

In [86]:
torch.empty(5, 3)

tensor([[                              0.0000,
         -158456325028528675187087900672.0000,
          -17089925541767652327313899520.0000],
        [                             -0.0000,
                                       0.0000,
                                       0.0000],
        [                              0.0000,
                                       0.0000,
                                       0.0000],
        [                              0.0000,
                                       0.0000,
                                       0.0000],
        [                              0.0000,
                                       0.0000,
                                       0.0000]])

In [87]:
torch.rand(5, 3)

tensor([[0.4292, 0.6363, 0.0528],
        [0.4464, 0.0182, 0.9922],
        [0.9377, 0.0366, 0.2856],
        [0.6985, 0.3749, 0.8752],
        [0.6468, 0.2499, 0.3874]])

In [88]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [90]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [92]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4446, -1.0974, -1.0828],
        [-0.7319, -0.3673, -1.0264],
        [ 2.2414, -0.4059, -1.8666],
        [ 0.7506,  0.4485,  0.4829],
        [ 0.4550,  0.9727, -0.2483]])


In [93]:
print(x.size())

torch.Size([5, 3])


In [94]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.0994, -0.9016, -0.9582],
        [ 0.2406,  0.1221, -0.4142],
        [ 3.0634,  0.4711, -1.5574],
        [ 1.6970,  0.5943,  1.3410],
        [ 0.6787,  1.2043, -0.1464]])


In [95]:
print(torch.add(x, y))

tensor([[ 1.0994, -0.9016, -0.9582],
        [ 0.2406,  0.1221, -0.4142],
        [ 3.0634,  0.4711, -1.5574],
        [ 1.6970,  0.5943,  1.3410],
        [ 0.6787,  1.2043, -0.1464]])


In [96]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0994, -0.9016, -0.9582],
        [ 0.2406,  0.1221, -0.4142],
        [ 3.0634,  0.4711, -1.5574],
        [ 1.6970,  0.5943,  1.3410],
        [ 0.6787,  1.2043, -0.1464]])


In [118]:
y.add_(x)
print(y)

tensor([[  6.4344, -14.0710, -13.9518],
        [ -8.5422,  -4.2850, -12.7316],
        [ 29.9603,  -4.3992, -23.9563],
        [ 10.7044,   5.9763,   7.1361],
        [  6.1384,  12.8765,  -3.1263]])


In [119]:
print(x[:, 1])

tensor([-1.0974, -0.3673, -0.4059,  0.4485,  0.9727])


In [122]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [125]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0620])
0.06197604909539223


## Numpy Bridge

In [126]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [127]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [128]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [131]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

In [132]:
torch.cuda.is_available()

False

In [133]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(x)
    print(z.to('cpu', torch.double))