# Chapter 2. 시퀀스

## 2.2 지능형 리스트와 제너레이터 표현식

In [2]:
symbols = '$¢¥€'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
    
codes

[36, 162, 165, 8364, 63743]

In [3]:
symbols = '$¢¥€'
codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 165, 8364, 63743]

In [4]:
x = 'ABC'
dummy = [ord(x) for x in x]
x

'ABC'

In [5]:
dummy

[65, 66, 67]

In [6]:
symbols = '$¢¥€'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
beyond_ascii

[162, 165, 8364, 63743]

In [8]:
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
beyond_ascii

[162, 165, 8364, 63743]

In [9]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [10]:
for color in colors:
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [11]:
tshirts = [(color, size) for size in sizes
                         for color in colors]
tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

In [12]:
symbols = '$¢¥€'
tuple(ord(symbol) for symbol in symbols)

(36, 162, 165, 8364, 63743)

In [16]:
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 165, 8364, 63743])

In [18]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirts in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirts)

black S
black M
black L
white S
white M
white L


## 2.3 튜플은 단순한 불변 리스트가 아니다

In [21]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokoy', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [22]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [23]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
latitude

33.9425

In [24]:
longitude

-118.408056

In [27]:
divmod(20, 8)

(2, 4)

In [29]:
t = (20, 8)
divmod(*t)

(2, 4)

In [31]:
quotient, reminder = divmod(*t)
quotient, reminder

(2, 4)

In [33]:
import os
_, filename = os.path.split('/home/luciano/.ssh./idrsa.pub')
filename

'idrsa.pub'

In [36]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [38]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [40]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [41]:
a, *body, c = range(5)
a, body, c

(0, [1, 2, 3], 4)

In [42]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [44]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [48]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),   
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat', 'long'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (lattiude, longtiude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, lattiude, longtiude))

                |    lat    |   long   
Tokyo           |   35.6897 |  139.6917
Delhi NCR       |   28.6139 |   77.2089
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


In [58]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [59]:
tokyo.population

36.933

In [60]:
tokyo.coordinates

(35.689722, 139.691667)

In [61]:
tokyo[1]

'JP'

In [64]:
City._fields

('name', 'country', 'population', 'coordinates')

In [68]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
delhi._asdict()

OrderedDict([('name', 'Delhi NCR'),
             ('country', 'IN'),
             ('population', 21.935),
             ('coordinates', LatLong(lat=28.613889, long=77.208889))])

## 2.4 슬라이싱

In [1]:
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [2]:
l[2:]

[30, 40, 50, 60]

In [3]:
l[:3]

[10, 20, 30]

In [4]:
l[3:]

[40, 50, 60]

In [20]:
s = 'bicycle'
s[::3]

'bye'

In [7]:
s[::-1]

'elcycib'

In [8]:
s[::-2]

'eccb'

In [19]:
sl = slice(0, 2)
l[sl]

[10, 20]

In [21]:
...

Ellipsis

In [58]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [60]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [61]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [62]:
l[2:5] = 100

TypeError: can only assign an iterable

In [63]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

## 2.5 시퀀스에 덧셈과 곱셈 연산자 사용하기

In [64]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [65]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [66]:
'abcd' * 5

'abcdabcdabcdabcdabcd'

In [68]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [69]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [71]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [73]:
weird_board[1][2] = 'X'
weird_board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [75]:
id(weird_board[0]), id(weird_board[1])

(4599317896, 4599317896)

## 2.6 시퀀스의 복합 할당(augmented assignment)

In [81]:
l = [1, 2, 3]
id(l)

4599828616

In [82]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [83]:
id(l)

4599828616

In [84]:
t = (1, 2, 3)
id(t)

4598239448

In [85]:
t *= 2
t

(1, 2, 3, 1, 2, 3)

In [86]:
id(t)

4598310280

In [87]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [88]:
t

(1, 2, [30, 40, 50, 60])

In [99]:
import dis
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


## 2.7 list.sort()와 sorted() 내장 함수

In [100]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [101]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [102]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [103]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [104]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [105]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [107]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

## 2.8 정렬된 시퀀스를 bisect로 관리하기

In [121]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))

In [122]:
bisect_fn = bisect.bisect
print('DEMO:', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
demo(bisect_fn)

DEMO: bisect
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [123]:
bisect_fn = bisect.bisect_left
print('DEMO:', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
demo(bisect_fn)

DEMO: bisect_left
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 12      |  |  |  |  |  |  |  |  |  |  |  |29
23 @  9      |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  4      |  |  |  |8 
 5 @  2      |  |5 
 2 @  1      |2 
 1 @  0    1 
 0 @  0    0 


In [126]:
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 80, 89, 90, 100]]

['F', 'A', 'C', 'B', 'B', 'A', 'A']

In [128]:
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


## 2.9 리스트가 답이 아닐 때

In [5]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.8673995559656226

In [12]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

0.8673995559656226

In [13]:
floats == floats2

True

In [22]:
import array

numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [23]:
memv[0]

-2

In [26]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [27]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [1]:
import numpy

a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
type(a)

numpy.ndarray

In [34]:
a.shape

(12,)

In [37]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a[2]

array([ 8,  9, 10, 11])

In [39]:
a[2, 1]

9

In [40]:
a[:, 1]

array([1, 5, 9])

In [41]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [2]:
floats = numpy.random.random(10**5)
floats[-3:]

array([ 0.86954767,  0.49260684,  0.44857707])

In [46]:
floats *= .5
floats[-3:]

array([ 0.09657349,  0.16851022,  0.37047452])

In [22]:
from time import perf_counter as pc
t0 = pc(); floats /= 3; pc() - t0

0.00029362599889282137

In [27]:
numpy.save('floats-10M.npy', floats)
floats2 = numpy.load('floats-10M.npy', 'r+')
floats *= 6
floats2[-3:]

memmap([  2.49383836e-10,   1.41278263e-10,   1.28650647e-10])

In [47]:
from collections import deque

dq = deque(range(10), 10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [49]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [50]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [52]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])

In [61]:
import queue
import multiprocessing
import asyncio
import heapq

## 뒷 이야기

In [62]:
l = [28, 14, '28', 5, '9', '1', 0, 6, '23', 19]
sorted(l)

TypeError: '<' not supported between instances of 'str' and 'int'

In [63]:
sorted(l, key=int)

[0, '1', 5, 6, '9', 14, 19, '23', 28, '28']

In [65]:
sorted(l, key=str)

[0, '1', 14, 19, '23', 28, '28', 5, 6, '9']